#!/usr/bin/env bash
set -e
sim=true
verbose=''
while getopts Sv OPT; do
  case "$OPT" in
    S)
      sim=false
      ;;
    v)
      verbose=-v
      ;;
  esac
done
shift "$(($OPTIND - 1))"
# download_dir="${1:-.}"

# Replace with the source code directory
download_dir=.

outdir="${2:-.}"
# url_base=http://parsec.cs.princeton.edu/download/3.0
# repodir="/home/lowell/Repo/PARSEC3"
basenames=''
basenames="$basenames parsec-3.0-core.tar.gz"
if "$sim"; then
  basenames="$basenames parsec-3.0-input-sim.tar.gz"
fi
# Huge. Impractical for simulators, intended for real silicon.
# parsec-3.0-input-native.tar.gz
mkdir -p "$outdir"
echo "${outdir}"
for basename in $basenames; do
  tar -xz -v -f "${download_dir}/${basename}" -C "$outdir" --skip-old-files --strip-components=1
done
